# This will be the first part of the title tag for your site <title> site.name + page.title </title>
name: "Stitch Fix Engineering & Algorithms Jobs"
# Populates the meta description for the site. Should be under 150 characters for best SEO purposes.
description: "Stitch Fix is a full-stack startup creating unique solutions in data-driven merchandising, massively scaled personal styling, and complex logistics."

author: "Stitch Fix"
url: "http://technology.stitchfix.com/"
title: "Stitch Fix Technology"
production_url: "http://technology.stitchfix.com"
atom_path: "atom.xml"

# Your UA tracking number (i.e 35858753-1) for Google Analytics.
# If you comment this out, or don't fill out this parameter - Google analytics won't be included.
# googleID: 25598599-8

# Pagination variable for how many posts to show in a list
paginate: 10

# Style of permalinks
permalink: /blog/:year/:month/:day/:title

# Variable format options for URL styles below
# pretty                                          => /2009/04/29/slap-chop/index.html
# /:month-month:day-:year/:title.html/            => 04-29-2009/slap-chop.html
# /blog/:year/:month/:day/:title                 => /blog/2009/04/29/slap-chop/index.html

exclude: [Rakefile, README.md, bower_components, bower.json]

markdown: redcarpet
redcarpet:
  extensions: ["tables"]

navigation:
 - title: Home
   url: "#intro"
 - title: Engineering
   url: "#engineering"
 - title: Data Science
   url: "#data-science"
 - title: Culture
   url: "#culture"
 - title: Team
   url: "#team"
 - title: Blog
   url: "/blog/"
 - title: Jobs
   url: "/jobs/"

assets:
  css_compressor: sass
  sources:
    - _assets/images
    - _assets/javascripts
    - _assets/stylesheets
    - bower_components

sass:
  style: :compressed
  load_paths: bower_components
